### PR TITLE
PR-3829 Bump engine version to latest version of 11.x

### PR DESCRIPTION
**Pull request by reweeden**
Cherry pick of #79 for master branch

### CODE REVIEW

**Review by lindsleycj — COMMENTED** [review]
Just noticed that the change log says bumping to version 10.18.  Are actually bumping to version 11.13

**Comment by reweeden** [comment]
Aaah, copy paste error!

**Comment by lindsleycj** [comment]
I'm fine with merging as is.  I can correct in the master branch when I create the next release.

**Comment by reweeden** [comment]
I fixed this PR, but the v11.1 branch will need to be fixed when you make the release for that.

**Comment by lindsleycj** [comment]
My plan is to create a full release when Cumulus releases the first patch version of v14.  Not sure if it is going to be named v14.1 or v14.0.1.  It is supposed to contain a fix that NSIDC needs.

**Comment by lindsleycj** [comment]
Oh, I can create the 11.1.8 release too.

**Pull request merged**
