### PR TITLE
PR-3829 Bump engine version to latest version of 11.x

### PR DESCRIPTION
**Pull request by reweeden**
We'll probably also need to merge these changes into master. I haven't really managed repos with multiple supported version branches before so I'm not really sure what the best approach is. Off the top of my head I'm thinking there are basically 2 choices:
1. Merge to v11 then merge v11 to master and resolve conflicts
2. Merge to v11 then cherry pick and make a new PR to master

### CODE REVIEW

**Review by lindsleycj — APPROVED** [review]
Looks good to me.

Whoops, was just looking at code changes.  I'm sort of thinking option 2 might be best.

**Comment by reweeden** [comment]
Yea from a quick stackoverflow search I'm getting the sense that 2 is the way to go.

**Comment by mattp0** [comment]
I was doing some testing, and using the `make rds` path to upgrade the stacks that are deployed ran into this issue:

```
Error: Failed to modify RDS Cluster (mrp-cumulus-dev-rds-cluster):
InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.
status code: 400, request id: f4b16747-cd13-4d27-9c38-6992337e49c7
```

I think this flag is not currently exposed to us via terraform. I briefly looked at cumulus and it might not be exposed from the module? https://github.com/nasa/cumulus/blob/master/tf-modules/cumulus-rds-tf/variables.tf

**Comment by mattp0** [comment]
A pathway I did test and succeed was using the AWS console and updating the engine manually

**Comment by lindsleycj** [comment]
That (AWS Console) is actually the way I'm planning to do the upgrade for ORNL.  I've always told our developers to only run `make rds` on initial install and never run it again.  I've always been concerned it might delete/recreate the actual database.

**Comment by reweeden** [comment]
Hmm, I'm still getting a similar error when trying to spin up a new stack from scratch:

```
Error: error creating RDS cluster: InvalidParameterCombination: The Parameter Group rew2-n-cumulus-dev-cluster-parameter-group with DBParameterGroupFamily aurora-postgresql10 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-postgresql11
	status code: 400, request id: 776ba274-2962-4254-9da3-3f091c7c6848
```

**Comment by lindsleycj** [comment]
@reweeden 

I think if you could add this extra variable to `rds/variables.tf`.

```
variable "parameter_group_family" {
  description = "Database family to use for creating database parameter group"
  type        = string
  default     = "aurora-postgresql11"
}
```

and then this line somewhere in the `rds/main.tf` in the rds_cluster module block:

```
  parameter_group_family   = var.parameter_group_family
```

I think we should be good.

**Comment by reweeden** [comment]
Adding `parameter_group_family` fixed it

**Pull request merged**
