### PR TITLE
Updated cumulus to v2.0.6

### PR DESCRIPTION
**Pull request by mckadesorensen**

### CODE REVIEW

**Comment by lindsleycj** [comment]
Hi, I haven't seen an official announcement of this release.  Maybe I missed it?  It's my understanding that the next release will require a number of Terraform changes to separate TEA from Cumulus.  Or maybe this release is a minor change before that bigger separation?  If this is the bigger release I'd want to make sure those other migration steps are included at least in the documentation.

**Comment by bbuechler** [comment]
> I haven't seen an official announcement of this release

Interesting question @lindsleycj . What is the official release stream? 

2.0.6 is the "latest" tagged release: https://github.com/nasa/cumulus/releases/latest

NPM Version is 2.0.6: [npm version](https://badge.fury.io/js/%40cumulus%2Fapi)

Last official Release in CHANGELOG.md is [paradoxically old @ 2.0.1](https://github.com/nasa/cumulus/blob/master/CHANGELOG.md#v201-2020-07-28).

**Comment by lindsleycj** [comment]
Generally, Lauren sends out a release email plus a Slack message in #cumulus-internal (note the one from Sept. 9).  Also, they update the release notes to include all the migration steps.  I have definitely seen releases weren't officially announced due to regression test failures, etc.  My general approach has been to wait for those notifications

**Comment by lindsleycj** [comment]
In the last Cumulus Integrators meeting Mark Boyd talked a good bit about the migration steps necessary to pull TEA out of the Cumulus fold without destroying your API Gateway.  Unfortunately, the agenda only shows the item to be discussed but no notes https://wiki.earthdata.nasa.gov/display/CUMULUS/2020-9-22+Meeting+Notes

**Comment by bbuechler** [comment]
I'm told the changes between 2.0.4 and 2.0.6 are minor, and 2.0.6 is the current version we should be using. Sounds like the major TEA changes are coming in v3. Should we not move forward with this @lindsleycj ?

**Comment by lindsleycj** [comment]
Yep, I'm fine with moving forward.

**Pull request merged**
